@startuml
'https://plantuml.com/activity-diagram-beta

[*] --> QuickBygFrontpage
QuickBygFrontpage --> StandardCarportPage
QuickBygFrontpage --> LoginPage
LoginPage --> QuickBygFrontpage
QuickBygFrontpage --> CustomerMadeCarportPage
LoginPage --> SignupPage
LoginPage <-- SignupPage
CustomerMadeCarportPage -->  QuickBygFladtTag
CustomerMadeCarportPage --> QuickBygHoejtTag




state LoggedOn {
QuickBygFrontpage --> Basket
StandardCarportPage --> OrderPage
DesignPage --> OrderPage
OrderPage --> CheckoutPage
CheckoutPage --> Basket

}

@enduml
